// Generated by CoffeeScript 1.7.1
(function() {
  var Channel, EventChannel;

  Channel = require("./channel");

  EventChannel = require("./event-channel");

  module.exports = EventChannel;

  module.exports.Channel = Channel;

  module.exports.EventChannel = EventChannel;

}).call(this);
